import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import api from '@/utils/api';
import { User, userSchema } from '@/utils/types';
import Link from 'next/link';
import { getCurrentUser } from '@/utils/helpers';
import LearningIcon from '@/ui/icons/LearningIcon';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const currentUser = await getCurrentUser();

	return (
		<html lang="en">
			<body className={`${inter.className} bg-slate-100`}>
				<nav className="flex items-center justify-between bg-slate-200 p-4">
					<h1>
						<Link href="/">Wordfulness</Link>
					</h1>
					<ul className="flex gap-8">
						{currentUser && (
							<>
								<li>
									<Link href="/learn">
										<LearningIcon />
									</Link>
								</li>
								<li>
									<Link href="/logout">Logout</Link>
								</li>
							</>
						)}
					</ul>
				</nav>
				{children}
			</body>
		</html>
	);
}
